# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lady = Category.create!(name:'レディース')
men = Category.create!(name:'メンズ')
baby = Category.create!(name:'ベビー・キッズ')
living = Category.create!(name:'インテリア・住まい・小物')
book = Category.create!(name:'本・音楽・ゲーム')
toy = Category.create!(name:'おもちゃ・ホビー・グッズ')
cosmetic = Category.create!(name:'コスメ・香水・美容')
electronics = Category.create!(name:'家電・スマホ・カメラ')
sport = Category.create!(name:'スポーツ・レジャー')
handmade = Category.create!(name:'ハンドメイド')
ticket = Category.create!(name:'チケット')
mobile = Category.create!(name:'自動車・オートバイ')
others = Category.create!(name:'その他')

lady_tops = lady.children.create!(name:'トップス')
lady_jacket = lady.children.create!(name:'ジャケット/アウター')
lady_pants = lady.children.create!(name:'パンツ')
lady_skirt = lady.children.create!(name:'スカート')
lady_onepiece= lady.children.create!(name:'ワンピース')
lady_shoes = lady.children.create!(name:'靴')
lady_roomwear = lady.children.create!(name:'ルームウェア/パジャマ')
lady_legwear = lady.children.create!(name:'レッグウェア')
lady_hat = lady.children.create!(name:'帽子')
lady_bag = lady.children.create!(name:'バッグ')
lady_acce = lady.children.create!(name:'アクセサリー')
lady_hairacce = lady.children.create!(name:'ヘアアクセサリー')
lady_item = lady.children.create!(name:'小物')
lady_watch = lady.children.create!(name:'時計')
lady_wig = lady.children.create!(name:'ウィッグ/エクステ')
lady_yukata = lady.children.create!(name:'浴衣/水着')
lady_suit = lady.children.create!(name:'スーツ/フォーマル/ドレス')
lady_matanity = lady.children.create!(name:'マタニティ')
lady_others = lady.children.create!(name:'その他')

lady_tops.children.create!([{name:'すべて', size_tag:1},{name:'Tシャツ/カットソー(半袖/袖なし)', size_tag:1},{name:'Tシャツ/カットソー(七分/長袖)', size_tag:1},{name:'シャツ/ブラウス(半袖/袖なし)', size_tag:1},{name:'シャツ/ブラウス(七分/長袖)', size_tag:1},{name:'ポロシャツ', size_tag:1},{name:'キャミソール', size_tag:1},{name:'タンクトップ', size_tag:1},{name:'ホルターネック', size_tag:1},{name:'ニット/セーター', size_tag:1},{name:'チュニック', size_tag:1},{name:'カーディガン/ボレロ', size_tag:1},{name:'アンサンブル', size_tag:1},{name:'ベスト/ジレ', size_tag:1},{name:'パーカー', size_tag:1},{name:'トレーナー/スウェット', size_tag:1},{name:'ベアトップ/チューブトップ', size_tag:1},{name:'ジャージ', size_tag:1},{name:'その他', size_tag:1},{name:'すべて', size_tag:1}])
lady_jacket.children.create!([{name:'テーラードジャケット', size_tag:1},{name:'ノーカラージャケット', size_tag:1},{name:'Gジャン/デニムジャケット', size_tag:1},{name:'レザージャケット', size_tag:1},{name:'ダウンジャケット', size_tag:1},{name:'ライダースジャケット', size_tag:1},{name:'ミリタリージャケット', size_tag:1},{name:'ダウンベスト', size_tag:1},{name:'ジャンパー/ブルゾン', size_tag:1},{name:'ポンチョ', size_tag:1},{name:'ロングコート', size_tag:1},{name:'トレンチコート', size_tag:1},{name:'ダッフルコート', size_tag:1},{name:'ピーコート', size_tag:1},{name:'チェスターコート', size_tag:1},{name:'モッズコート', size_tag:1},{name:'スタジャン', size_tag:1},{name:'毛皮/ファーコート', size_tag:1},{name:'スプリングコート', size_tag:1},{name:'スカジャン', size_tag:1},{name:'その他', size_tag:1}])
lady_pants.children.create!([{name:'すべて', size_tag:1},{name:'デニム/ジーンズ', size_tag:1},{name:'ショートパンツ', size_tag:1},{name:'カジュアルパンツ', size_tag:1},{name:'ハーフパンツ', size_tag:1},{name:'チノパン', size_tag:1},{name:'ワークパンツ/カーゴパンツ', size_tag:1},{name:'クロップドパンツ', size_tag:1},{name:'サロペット/オーバーオール', size_tag:1},{name:'オールインワン', size_tag:1},{name:'サルエルパンツ', size_tag:1},{name:'ガウチョパンツ', size_tag:1},{name:'その他', size_tag:1}])
lady_skirt.children.create!([{name:'すべて', size_tag:4},{name:'ミニスカート', size_tag:4},{name:'ひざ丈スカート', size_tag:4},{name:'ロングスカート', size_tag:4},{name:'キュロット', size_tag:4},{name:'その他', size_tag:4}])
lady_onepiece.children.create!([{name:'すべて', size_tag:1},{name:'ミニワンピース', size_tag:1},{name:'ひざ丈ワンピース', size_tag:1},{name:'ロングワンピース', size_tag:1},{name:'その他', size_tag:1}])
lady_shoes.children.create!([{name:'すべて', size_tag:3},{name:'ハイヒール/パンプス', size_tag:3},{name:'ブーツ', size_tag:3},{name:'サンダル', size_tag:3},{name:'スニーカー', size_tag:3},{name:'ミュール', size_tag:3},{name:'モカシン', size_tag:3},{name:'ローファー/革靴', size_tag:3},{name:'フラットシューズ/バレエシューズ', size_tag:3},{name:'長靴/レインシューズ', size_tag:3},{name:'その他', size_tag:3}])
lady_roomwear.children.create!([{name:'すべて', size_tag:1},{name:'パジャマ', size_tag:1},{name:'ルームウェア', size_tag:1}])
lady_legwear.children.create!([{name:'すべて'},{name:'ソックス'},{name:'スパッツ/レギンス'},{name:'ストッキング/タイツ'},{name:'レッグウォーマー'},{name:'その他'}])
lady_hat.children.create!([{name:'すべて'},{name:'ニットキャップ/ビーニー'},{name:'ハット'},{name:'ハンチング/ベレー帽'},{name:'キャップ'},{name:'キャスケット'},{name:'麦わら帽子'},{name:'その他'}])
lady_bag.children.create!([{name:'すべて'},{name:'ハンドバッグ'},{name:'トートバッグ'},{name:'エコバッグ'},{name:'リュック/バックパック'},{name:'ボストンバッグ'},{name:'スポーツバッグ'},{name:'ショルダーバッグ'},{name:'クラッチバッグ'},{name:'ポーチ/バニティ'},{name:'ボディバッグ/ウェストバッグ'},{name:'マザーズバッグ'},{name:'メッセンジャーバッグ'},{name:'ビジネスバッグ'},{name:'旅行用バッグ/キャリーバッグ'},{name:'ショップ袋'},{name:'和装用バッグ'},{name:'かごバッグ'},{name:'その他'}])
lady_acce.children.create!([{name:'すべて'},{name:'ネックレス'},{name:'ブレスレット'},{name:'バングル/リストバンド'},{name:'リング'},{name:'ピアス(片耳用)'},{name:'ピアス(両耳用)'},{name:'イヤリング'},{name:'アンクレット'},{name:'ブローチ/コサージュ'},{name:'チャーム'},{name:'その他'}])
lady_hairacce.children.create!([{name:'すべて'},{name:'ヘアゴム/シュシュ'},{name:'ヘアバンド/カチューシャ'},{name:'ヘアピン'},{name:'その他'}])
lady_item.children.create!([{name:'すべて'},{name:'長財布'},{name:'折り財布'},{name:'コインケース/小銭入れ'},{name:'名刺入れ/定期入れ'},{name:'キーケース'},{name:'キーホルダー'},{name:'手袋/アームカバー'},{name:'ハンカチ'},{name:'ベルト'},{name:'マフラー/ショール'},{name:'ストール/スヌード'},{name:'バンダナ/スカーフ'},{name:'ネックウォーマー'},{name:'サスペンダー'},{name:'サングラス/メガネ'},{name:'モバイルケース/カバー'},{name:'手帳'},{name:'イヤマフラー'},{name:'傘'},{name:'レインコート/ポンチョ'},{name:'ミラー'},{name:'タバコグッズ'},{name:'その他'}])
lady_watch.children.create!([{name:'すべて'},{name:'腕時計(アナログ)'},{name:'腕時計(デジタル)'},{name:'ラバーベルト'},{name:'レザーベルト'},{name:'金属ベルト'},{name:'その他'}])
lady_wig.children.create!([{name:'すべて'},{name:'前髪ウィッグ'},{name:'ロングストレート'},{name:'ロングカール'},{name:'ショートストレート'},{name:'ショートカール'},{name:'その他'}])
lady_yukata.children.create!([{name:'すべて', size_tag:1},{name:'浴衣', size_tag:1},{name:'着物', size_tag:1},{name:'振袖', size_tag:1},{name:'長襦袢/半襦袢', size_tag:1},{name:'水着セパレート', size_tag:1},{name:'水着ワンピース', size_tag:1},{name:'水着スポーツ用', size_tag:1},{name:'その他', size_tag:1}])
lady_suit.children.create!([{name:'すべて', size_tag:1},{name:'スカートスーツ上下', size_tag:1},{name:'パンツスーツ上下', size_tag:1},{name:'ドレス', size_tag:1},{name:'パーティーバッグ', size_tag:1},{name:'シューズ', size_tag:1},{name:'ウェディング', size_tag:1},{name:'その他', size_tag:1}])
lady_matanity.children.create!([{name:'すべて'},{name:'トップス'},{name:'アウター'},{name:'インナー'},{name:'ワンピース'},{name:'パンツ/スパッツ'},{name:'スカート'},{name:'パジャマ'},{name:'授乳服'},{name:'その他'}])
lady_others.children.create!([{name:'すべて'},{name:'コスプレ'},{name:'下着'},{name:'その他'}])
  


men_tops = men.children.create!(name:'トップス')
men_jacket = men.children.create!(name:'ジャケット/アウター')
men_pants = men.children.create!(name:'パンツ')
men_shoes = men.children.create!(name:'靴')
men_bag = men.children.create!(name:'バッグ')
men_suit = men.children.create!(name:'スーツ')
men_hat = men.children.create!(name:'帽子')
men_acce = men.children.create!(name:'アクセサリー')
men_item = men.children.create!(name:'小物')
men_watch = men.children.create!(name:'時計')
men_swimwear = men.children.create!(name:'水着')
men_legwear = men.children.create!(name:'レッグウェア')
men_underwear = men.children.create!(name:'アンダーウェア')
men_others = men.children.create!(name:'その他')

men_tops.children.create!([{name:'すべて', size_tag:1},{name:'Tシャツ/カットソー(半袖/袖なし)', size_tag:1},{name:'Tシャツ/カットソー(七分/長袖)', size_tag:1},{name:'シャツ', size_tag:1},{name:'ポロシャツ', size_tag:1},{name:'タンクトップ', size_tag:1},{name:'ニット/セーター', size_tag:1},{name:'パーカー', size_tag:1},{name:'カーディガン', size_tag:1},{name:'スウェット', size_tag:1},{name:'ジャージ', size_tag:1},{name:'ベスト', size_tag:1},{name:'その他', size_tag:1}])
men_jacket.children.create!([{name:'すべて', size_tag:1},{name:'テーラードジャケット', size_tag:1},{name:'ノーカラージャケット', size_tag:1},{name:'Gジャン/デニムジャケット', size_tag:1},{name:'レザージャケット', size_tag:1},{name:'ダウンジャケット', size_tag:1},{name:'ライダースジャケット', size_tag:1},{name:'ミリタリージャケット', size_tag:1},{name:'ナイロンジャケット', size_tag:1},{name:'フライトジャケット', size_tag:1},{name:'ダッフルコート', size_tag:1},{name:'ピーコート', size_tag:1},{name:'ステンカラーコート', size_tag:1},{name:'トレンチコート', size_tag:1},{name:'モッズコート', size_tag:1},{name:'チェスターコート', size_tag:1},{name:'スタジャン', size_tag:1},{name:'スカジャン', size_tag:1},{name:'ブルゾン', size_tag:1},{name:'マウンテンパーカー', size_tag:1},{name:'ダウンベスト', size_tag:1},{name:'ポンチョ', size_tag:1},{name:'カバーオール', size_tag:1},{name:'その他', size_tag:1}])
men_pants.children.create!([{name:'すべて', size_tag:1},{name:'デニム/ジーンズ', size_tag:1},{name:'ワークパンツ/カーゴパンツ', size_tag:1},{name:'スラックス', size_tag:1},{name:'チノパン', size_tag:1},{name:'ショートパンツ', size_tag:1},{name:'ペインターパンツ', size_tag:1},{name:'サルエルパンツ', size_tag:1},{name:'オーバーオール', size_tag:1},{name:'その他', size_tag:1}])
men_shoes.children.create!([{name:'すべて', size_tag:2},{name:'スニーカー', size_tag:2},{name:'サンダル', size_tag:2},{name:'ブーツ', size_tag:2},{name:'モカシン', size_tag:2},{name:'ドレス/ビジネス', size_tag:2},{name:'長靴/レインシューズ', size_tag:2},{name:'デッキシューズ', size_tag:2},{name:'その他', size_tag:2}])
men_bag.children.create!([{name:'すべて', size_tag:1},{name:'ショルダーバッグ', size_tag:1},{name:'トートバッグ', size_tag:1},{name:'ボストンバッグ', size_tag:1},{name:'リュック/バックパック', size_tag:1},{name:'ウエストポーチ', size_tag:1},{name:'ボディーバッグ', size_tag:1},{name:'ドラムバッグ', size_tag:1},{name:'ビジネスバッグ', size_tag:1},{name:'トラベルバッグ', size_tag:1},{name:'メッセンジャーバッグ', size_tag:1},{name:'エコバッグ', size_tag:1},{name:'その他', size_tag:1}])
men_suit.children.create!([{name:'すべて', size_tag:1},{name:'スーツジャケット', size_tag:1},{name:'スーツベスト', size_tag:1},{name:'スラックス', size_tag:1},{name:'セットアップ', size_tag:1},{name:'その他', size_tag:1}])
men_hat.children.create!([{name:'すべて'},{name:'キャップ'},{name:'ハット'},{name:'ニットキャップ/ビーニー'},{name:'ハンチング/ベレー帽'},{name:'キャスケット'},{name:'サンバイザー'},{name:'その他'}])
men_acce.children.create!([{name:'すべて'},{name:'ネックレス'},{name:'ブレスレット'},{name:'バングル/リストバンド'},{name:'リング'},{name:'ピアス(片耳用)'},{name:'ピアス(両耳用)'},{name:'アンクレット'},{name:'その他'}])
men_item.children.create!([{name:'すべて'},{name:'長財布'},{name:'折り財布'},{name:'マネークリップ'},{name:'コインケース/小銭入れ'},{name:'名刺入れ/定期入れ'},{name:'キーケース'},{name:'キーホルダー'},{name:'ネクタイ'},{name:'手袋'},{name:'ハンカチ'},{name:'ベルト'},{name:'マフラー'},{name:'ストール'},{name:'バンダナ'},{name:'ネックウォーマー'},{name:'サスペンダー'},{name:'ウォレットチェーン'},{name:'サングラス/メガネ'},{name:'モバイルケース/カバー'},{name:'手帳'},{name:'ストラップ'},{name:'ネクタイピン'},{name:'カフリンクス'},{name:'イヤマフラー'},{name:'傘'},{name:'レインコート'},{name:'ミラー'},{name:'タバコグッズ'},{name:'その他'}])
men_watch.children.create!([{name:'すべて'},{name:'腕時計(アナログ)'},{name:'腕時計(デジタル)'},{name:'ラバーベルト'},{name:'レザーベルト'},{name:'金属ベルト'},{name:'その他'}])
men_swimwear.children.create!([{name:'すべて', size_tag:1},{name:'一般水着', size_tag:1},{name:'スポーツ用', size_tag:1},{name:'アクセサリー', size_tag:1},{name:'その他', size_tag:1}])
men_legwear.children.create!([{name:'すべて'},{name:'ソックス'},{name:'レギンス/スパッツ'},{name:'レッグウォーマー'},{name:'その他'}])
men_underwear.children.create!([{name:'すべて'},{name:'トランクス'},{name:'ボクサーパンツ'},{name:'その他'}])
men_others.children.create!([{name:'すべて'}])


baby_w_small = baby.children.create!(name:'ベビー服(女の子用)~95cm')
baby_m_small = baby.children.create!(name:'ベビー服(男の子用)~95cm')
baby_u_small = baby.children.create!(name:'ベビー服(男女兼用)~95cm')
baby_w_large = baby.children.create!(name:'キッズ服(女の子用)100cm~')
baby_m_large = baby.children.create!(name:'キッズ服(男の子用)100cm~')
baby_u_large = baby.children.create!(name:'キッズ服(男女兼用)100cm~')
baby_shoes = baby.children.create!(name:'キッズ靴')
baby_item = baby.children.create!(name:'子ども用ファッション小物')
baby_toilet = baby.children.create!(name:'おむつ/トイレ/バス')
baby_out = baby.children.create!(name:'外出/移動用品')
baby_meal = baby.children.create!(name:'授乳/食事')
baby_furniture = baby.children.create!(name:'ベビー家具/寝具/室内用品')
baby_toy = baby.children.create!(name:'おもちゃ')
baby_event = baby.children.create!(name:'行事/記念品')
baby_others = baby.children.create!(name:'その他')



baby_w_small.children.create!([{name:'すべて', size_tag:7},{name:'トップス', size_tag:7},{name:'アウター', size_tag:7},{name:'パンツ', size_tag:7},{name:'スカート', size_tag:7},{name:'ワンピース', size_tag:7},{name:'ベビードレス', size_tag:7},{name:'おくるみ', size_tag:7},{name:'下着/肌着', size_tag:7},{name:'パジャマ', size_tag:7},{name:'ロンパース', size_tag:7},{name:'その他', size_tag:7}])
baby_m_small.children.create!([{name:'すべて', size_tag:7},{name:'トップス', size_tag:7},{name:'アウター', size_tag:7},{name:'パンツ', size_tag:7},{name:'おくるみ', size_tag:7},{name:'下着/肌着', size_tag:7},{name:'パジャマ', size_tag:7},{name:'ロンパース', size_tag:7},{name:'その他', size_tag:7}])
baby_u_small.children.create!([{name:'すべて', size_tag:7},{name:'トップス', size_tag:7},{name:'アウター', size_tag:7},{name:'パンツ', size_tag:7},{name:'おくるみ', size_tag:7},{name:'下着/肌着', size_tag:7},{name:'パジャマ', size_tag:7},{name:'ロンパース', size_tag:7},{name:'その他', size_tag:7}])
baby_w_large.children.create!([{name:'すべて', size_tag:5},{name:'コート', size_tag:5},{name:'ジャケット/上着', size_tag:5},{name:'トップス(Tシャツ/カットソー)', size_tag:5},{name:'トップス(トレーナー)', size_tag:5},{name:'トップス(チュニック)', size_tag:5},{name:'トップス(タンクトップ)', size_tag:5},{name:'トップス(その他)', size_tag:5},{name:'スカート', size_tag:5},{name:'パンツ', size_tag:5},{name:'ワンピース', size_tag:5},{name:'セットアップ', size_tag:5},{name:'パジャマ', size_tag:5},{name:'フォーマル/ドレス', size_tag:5},{name:'和服', size_tag:5},{name:'浴衣', size_tag:5},{name:'甚平', size_tag:5},{name:'水着', size_tag:5},{name:'その他', size_tag:5}])
baby_m_large.children.create!([{name:'すべて', size_tag:5},{name:'コート', size_tag:5},{name:'ジャケット/上着', size_tag:5},{name:'トップス(Tシャツ/カットソー)', size_tag:5},{name:'トップス(トレーナー)', size_tag:5},{name:'トップス(その他)', size_tag:5},{name:'パンツ', size_tag:5},{name:'セットアップ', size_tag:5},{name:'パジャマ', size_tag:5},{name:'フォーマル/ドレス', size_tag:5},{name:'和服', size_tag:5},{name:'浴衣', size_tag:5},{name:'甚平', size_tag:5},{name:'水着', size_tag:5},{name:'その他', size_tag:5}])
baby_u_large.children.create!([{name:'すべて', size_tag:5},{name:'コート', size_tag:5},{name:'ジャケット/上着', size_tag:5},{name:'トップス(Tシャツ/カットソー)', size_tag:5},{name:'トップス(トレーナー)', size_tag:5},{name:'トップス(その他)', size_tag:5},{name:'ボトムス', size_tag:5},{name:'パジャマ', size_tag:5},{name:'その他', size_tag:5}])
baby_shoes.children.create!([{name:'すべて', size_tag:6},{name:'スニーカー', size_tag:6},{name:'サンダル', size_tag:6},{name:'ブーツ', size_tag:6},{name:'長靴', size_tag:6},{name:'その他', size_tag:6}])
baby_item.children.create!([{name:'すべて'},{name:'靴下/スパッツ'},{name:'帽子'},{name:'エプロン'},{name:'サスペンダー'},{name:'タイツ'},{name:'ハンカチ'},{name:'バンダナ'},{name:'ベルト'},{name:'マフラー'},{name:'傘'},{name:'手袋'},{name:'スタイ'},{name:'バッグ'},{name:'その他'}])
baby_toilet.children.create!([{name:'すべて'},{name:'おむつ用品'},{name:'おまる/補助便座'},{name:'トレーニングパンツ'},{name:'ベビーバス'},{name:'お風呂用品'},{name:'その他'}])
baby_out.children.create!([{name:'すべて'},{name:'ベビーカー'},{name:'抱っこひも/スリング'},{name:'チャイルドシート'},{name:'その他'}])
baby_meal.children.create!([{name:'すべて'},{name:'ミルク'},{name:'ベビーフード'},{name:'ベビー用食器'},{name:'その他'}])
baby_furniture.children.create!([{name:'すべて'},{name:'ベッド'},{name:'布団/毛布'},{name:'イス'},{name:'たんす'},{name:'その他'}])
baby_toy.children.create!([{name:'すべて'},{name:'おふろのおもちゃ'},{name:'がらがら'},{name:'オルゴール'},{name:'ベビージム'},{name:'手押し車/カタカタ'},{name:'知育玩具'},{name:'その他'}])
baby_event.children.create!([{name:'すべて'},{name:'お宮参り用品'},{name:'お食い初め用品'},{name:'アルバム'},{name:'手形/足形'},{name:'その他'}])
baby_others.children.create!([{name:'すべて'},{name:'母子手帳用品'},{name:'その他'}])



living_dish = living.children.create!(name:'キッチン/食器')
living_bed = living.children.create!(name:'ベッド/マットレス')
living_sofa = living.children.create!(name:'ソファ/ソファベッド')
living_chair = living.children.create!(name:'椅子/チェア')
living_table = living.children.create!(name:'机/テーブル')
living_storage = living.children.create!(name:'収納家具')
living_carpet = living.children.create!(name:'ラグ/カーペット/マット')
living_cartain = living.children.create!(name:'カーテン/ブラインド')
living_light = living.children.create!(name:'ライト/照明')
living_furniture = living.children.create!(name:'寝具')
living_item = living.children.create!(name:'インテリア小物')
living_events = living.children.create!(name:'季節/年中行事')
living_others = living.children.create!(name:'その他')

living_dish.children.create!([{name:'すべて'},{name:'食器'},{name:'調理器具'},{name:'収納/キッチン雑貨'},{name:'弁当用品'},{name:'カトラリー(スプーン等)'},{name:'テーブル用品'},{name:'容器'},{name:'エプロン'},{name:'アルコールグッズ'},{name:'浄水機'},{name:'その他'}])
living_bed.children.create!([{name:'すべて'},{name:'セミシングルベッド'},{name:'シングルベッド'},{name:'セミダブルベッド'},{name:'ダブルベッド'},{name:'ワイドダブルベッド'},{name:'クイーンベッド'},{name:'キングベッド'},{name:'脚付きマットレスベッド'},{name:'マットレス'},{name:'すのこベッド'},{name:'ロフトベッド/システムベッド'},{name:'簡易ベッド/折りたたみベッド'},{name:'収納付き'},{name:'その他'}])
living_sofa.children.create!([{name:'すべて'},{name:'ソファセット'},{name:'シングルソファ'},{name:'ラブソファ'},{name:'トリプルソファ'},{name:'オットマン'},{name:'コーナーソファ'},{name:'ビーズソファ/クッションソファ'},{name:'ローソファ/フロアソファ'},{name:'ソファベッド'},{name:'応接セット'},{name:'ソファカバー'},{name:'リクライニングソファ'},{name:'その他'}])
living_chair.children.create!([{name:'すべて'},{name:'一般'},{name:'スツール'},{name:'ダイニングチェア'},{name:'ハイバックチェア'},{name:'ロッキングチェア'},{name:'座椅子'},{name:'折り畳みイス'},{name:'デスクチェア'},{name:'その他'}])
living_table.children.create!([{name:'すべて'},{name:'こたつ'},{name:'カウンターテーブル'},{name:'サイドテーブル'},{name:'センターテーブル'},{name:'ダイニングテーブル'},{name:'座卓/ちゃぶ台'},{name:'アウトドア用'},{name:'パソコン用'},{name:'事務机/学習机'},{name:'その他'}])
living_storage.children.create!([{name:'すべて'},{name:'リビング収納'},{name:'キッチン収納'},{name:'玄関/屋外収納'},{name:'バス/トイレ収納'},{name:'本収納'},{name:'本/CD/DVD収納'},{name:'洋服タンス/押入れ収納'},{name:'電話台/ファックス台'},{name:'ドレッサー/鏡台'},{name:'棚/ラック'},{name:'ケース/ボックス'},{name:'その他'}])
living_carpet.children.create!([{name:'すべて'},{name:'ラグ'},{name:'カーペット'},{name:'ホットカーペット'},{name:'玄関/キッチンマット'},{name:'トイレ/バスマット'},{name:'その他'}])
living_cartain.children.create!([{name:'すべて'},{name:'カーテン'},{name:'ブラインド'},{name:'ロールスクリーン'},{name:'のれん'},{name:'その他'}])
living_light.children.create!([{name:'すべて'},{name:'蛍光灯/電球'},{name:'天井照明'},{name:'フロアスタンド'},{name:'その他'}])
living_furniture.children.create!([{name:'すべて'},{name:'布団/毛布'},{name:'枕'},{name:'シーツ/カバー'},{name:'その他'}])
living_item.children.create!([{name:'すべて'},{name:'ごみ箱'},{name:'ウェルカムボード'},{name:'オルゴール'},{name:'クッション'},{name:'クッションカバー'},{name:'スリッパラック'},{name:'ティッシュボックス'},{name:'バスケット/かご'},{name:'フォトフレーム'},{name:'マガジンラック'},{name:'モビール'},{name:'花瓶'},{name:'灰皿'},{name:'傘立て'},{name:'小物入れ'},{name:'置時計'},{name:'掛時計/柱時計'},{name:'鏡(立て掛け式)'},{name:'鏡(壁掛け式)'},{name:'置物'},{name:'風鈴'},{name:'植物/観葉植物'},{name:'その他'}])
living_events.children.create!([{name:'すべて'},{name:'正月'},{name:'成人式'},{name:'バレンタインデー'},{name:'ひな祭り'},{name:'子どもの日'},{name:'母の日'},{name:'父の日'},{name:'サマーギフト/お中元'},{name:'夏/夏休み'},{name:'ハロウィン'},{name:'敬老の日'},{name:'七五三'},{name:'お歳暮'},{name:'クリスマス'},{name:'冬一般'},{name:'その他'}])
living_others.children.create!([{name:'すべて'}])



book_book = book.children.create!(name:'本')
book_comic = book.children.create!(name:'漫画')
book_magazine = book.children.create!(name:'雑誌')
book_CD = book.children.create!(name:'CD')
book_DVD = book.children.create!(name:'DVD/ブルーレイ')
book_record = book.children.create!(name:'レコード')
book_TVgame = book.children.create!(name:'テレビゲーム')



book_book.children.create!([{name:'すべて'},{name:'文学/小説'},{name:'人文/社会'},{name:'ノンフィクション/教養'},{name:'地図/旅行ガイド'},{name:'ビジネス/経済'},{name:'健康/医学'},{name:'コンピュータ/IT'},{name:'趣味/スポーツ/実用'},{name:'住まい/暮らし/子育て'},{name:'アート/エンタメ'},{name:'洋書'},{name:'絵本'},{name:'参考書'},{name:'その他'}])
book_comic.children.create!([{name:'すべて'},{name:'全巻セット'},{name:'少年漫画'},{name:'少女漫画'},{name:'青年漫画'},{name:'女性漫画'},{name:'同人誌'},{name:'その他'}])
book_magazine.children.create!([{name:'すべて'},{name:'アート/エンタメ/ホビー'},{name:'ファッション'},{name:'ニュース/総合'},{name:'趣味/スポーツ'},{name:'その他'}])
book_CD.children.create!([{name:'すべて'},{name:'邦楽'},{name:'洋楽'},{name:'アニメ'},{name:'クラシック'},{name:'K-POP/アジア'},{name:'キッズ/ファミリー'},{name:'その他'}])
book_DVD.children.create!([{name:'すべて'},{name:'外国映画'},{name:'日本映画'},{name:'アニメ'},{name:'TVドラマ'},{name:'ミュージック'},{name:'お笑い/バラエティ'},{name:'スポーツ/フィットネス'},{name:'キッズ/ファミリー'},{name:'その他'}])
book_record.children.create!([{name:'すべて'},{name:'邦楽'},{name:'洋楽'},{name:'その他'}])
book_TVgame.children.create!([{name:'すべて'},{name:'家庭用ゲーム本体'},{name:'家庭用ゲームソフト'},{name:'携帯用ゲーム本体'},{name:'携帯用ゲームソフト'},{name:'PCゲーム'},{name:'その他'}])


toy_toy = toy.children.create!(name:'おもちゃ')
toy_talent_goods= toy.children.create!(name:'タレントグッズ')
toy_comic = toy.children.create!(name:'コミック/アニメグッズ')
toy_trading_card= toy.children.create!(name:'トレーディングカード')
toy_figure = toy.children.create!(name:'フィギュア')
toy_instrument = toy.children.create!(name:'楽器/器材')
toy_collection = toy.children.create!(name:'コレクション')
toy_military = toy.children.create!(name:'ミリタリー')
toy_art = toy.children.create!(name:'美術品')
toy_art_goods = toy.children.create!(name:'アート用品')
toy_others = toy.children.create!(name:'その他')

toy_toy.children.create!([{name:'すべて'},{name:'キャラクターグッズ'},{name:'ぬいぐるみ'},{name:'小物/アクセサリー'},{name:'模型/プラモデル'},{name:'ミニカー'},{name:'トイラジコン'},{name:'プラモデル'},{name:'ホビーラジコン'},{name:'鉄道模型'},{name:'その他'}])
toy_talent_goods.children.create!([{name:'すべて'},{name:'アイドル'},{name:'ミュージシャン'},{name:'タレント/お笑い芸人'},{name:'スポーツ選手'},{name:'その他'}])
toy_comic.children.create!([{name:'すべて'},{name:'ストラップ'},{name:'キーホルダー'},{name:'バッジ'},{name:'カード'},{name:'クリアファイル'},{name:'ポスター'},{name:'タオル'},{name:'その他'}])
toy_trading_card.children.create!([{name:'すべて'},{name:'遊戯王'},{name:'マジック：ザ・ギャザリング'},{name:'ポケモンカードゲーム'},{name:'デュエルマスターズ'},{name:'バトルスピリッツ'},{name:'プリパラ'},{name:'アイカツ'},{name:'カードファイト!!ヴァンガード'},{name:'ヴァイスシュヴァルツ'},{name:'プロ野球オーナーズリーグ'},{name:'ベースボールヒーローズ'},{name:'ドラゴンボール'},{name:'スリーブ'},{name:'その他'}])
toy_figure.children.create!([{name:'すべて'},{name:'コミック/アニメ'},{name:'特撮'},{name:'ゲームキャラクター'},{name:'SF/ファンタジー/ホラー'},{name:'アメコミ'},{name:'スポーツ'},{name:'ミリタリー'},{name:'その他'}])
toy_instrument.children.create!([{name:'すべて'},{name:'エレキギター'},{name:'アコースティックギター'},{name:'ベース'},{name:'エフェクター'},{name:'アンプ'},{name:'弦楽器'},{name:'管楽器'},{name:'鍵盤楽器'},{name:'打楽器'},{name:'和楽器'},{name:'楽譜/スコア'},{name:'レコーディング/PA機器'},{name:'DJ機器'},{name:'DTM/DAW'},{name:'その他'}])
toy_collection.children.create!([{name:'すべて'},{name:'武具'},{name:'使用済切手/官製はがき'},{name:'旧貨幣/金貨/銀貨/記念硬貨'},{name:'印刷物'},{name:'ノベルティグッズ'},{name:'その他'}])
toy_military.children.create!([{name:'すべて'},{name:'トイガン'},{name:'個人装備'},{name:'その他'}])
toy_art.children.create!([{name:'すべて'},{name:'陶芸'},{name:'ガラス'},{name:'漆芸'},{name:'金属工芸'},{name:'絵画/タペストリ'},{name:'版画'},{name:'彫刻/オブジェクト'},{name:'書'},{name:'写真'},{name:'その他'}])
toy_art_goods.children.create!([{name:'すべて'},{name:'画材'},{name:'額縁'},{name:'その他'}])
toy_others.children.create!([{name:'すべて'},{name:'トランプ/UNO'},{name:'カルタ/百人一首'},{name:'ダーツ'},{name:'ビリヤード'},{name:'麻雀'},{name:'パズル/ジグソーパズル'},{name:'囲碁/将棋'},{name:'オセロ/チェス'},{name:'人生ゲーム'},{name:'野球/サッカーゲーム'},{name:'スポーツ'},{name:'三輪車/乗り物'},{name:'ヨーヨー'},{name:'模型製作用品'},{name:'鉄道'},{name:'航空機'},{name:'アマチュア無線'},{name:'パチンコ/パチスロ'},{name:'その他'}])



cosmetic_basemake = cosmetic.children.create!(name:'ベースメイク')
cosmetic_makeup = cosmetic.children.create!(name:'メイクアップ')
cosmetic_nail = cosmetic.children.create!(name:'ネイルケア')
cosmetic_perfume = cosmetic.children.create!(name:'香水')
cosmetic_skincare = cosmetic.children.create!(name:'スキンケア/基礎化粧品')
cosmetic_haircare = cosmetic.children.create!(name:'ヘアケア')
cosmetic_bodycare = cosmetic.children.create!(name:'ボディケア')
cosmetic_oralcare = cosmetic.children.create!(name:'オーラルケア')
cosmetic_relax = cosmetic.children.create!(name:'リラクゼーション')
cosmetic_diet = cosmetic.children.create!(name:'ダイエット')
cosmetic_others = cosmetic.children.create!(name:'その他')

cosmetic_basemake.children.create!([{name:'すべて'},{name:'ファンデーション'},{name:'化粧下地'},{name:'コントロールカラー'},{name:'BBクリーム'},{name:'CCクリーム'},{name:'コンシーラー'},{name:'フェイスパウダー'},{name:'トライアルセット/サンプル'},{name:'その他'}])
cosmetic_makeup.children.create!([{name:'すべて'},{name:'アイシャドウ'},{name:'口紅'},{name:'リップグロス'},{name:'リップライナー'},{name:'チーク'},{name:'フェイスカラー'},{name:'マスカラ'},{name:'アイライナー'},{name:'つけまつげ'},{name:'アイブロウペンシル'},{name:'パウダーアイブロウ'},{name:'眉マスカラ'},{name:'トライアルセット/サンプル'},{name:'メイク道具/化粧小物'},{name:'美顔用品/美顔ローラー'},{name:'その他'}])
cosmetic_nail.children.create!([{name:'すべて'},{name:'ネイルカラー'},{name:'カラージェル'},{name:'ネイルベースコート/トップコート'},{name:'ネイルアート用品'},{name:'ネイルパーツ'},{name:'ネイルチップ/付け爪'},{name:'手入れ用具'},{name:'除光液'},{name:'その他'}])
cosmetic_perfume.children.create!([{name:'すべて'},{name:'香水(女性用)'},{name:'香水(男性用)'},{name:'ユニセックス'},{name:'ボディミスト'},{name:'その他'}])
cosmetic_skincare.children.create!([{name:'すべて'},{name:'化粧水/ローション'},{name:'乳液/ミルク'},{name:'美容液'},{name:'フェイスクリーム'},{name:'洗顔料'},{name:'クレンジング/メイク落とし'},{name:'パック/フェイスマスク'},{name:'ジェル/ゲル'},{name:'ブースター/導入液'},{name:'アイケア'},{name:'リップケア'},{name:'トライアルセット/サンプル'},{name:'洗顔グッズ'},{name:'その他'}])
cosmetic_haircare.children.create!([{name:'すべて'},{name:'シャンプー'},{name:'トリートメント'},{name:'コンディショナー'},{name:'リンス'},{name:'スタイリング剤'},{name:'カラーリング剤'},{name:'ブラシ'},{name:'その他'}])
cosmetic_bodycare.children.create!([{name:'すべて'},{name:'オイル/クリーム'},{name:'ハンドクリーム'},{name:'ローション'},{name:'日焼け止め/サンオイル'},{name:'ボディソープ'},{name:'入浴剤'},{name:'制汗/デオドラント'},{name:'フットケア'},{name:'その他'}])
cosmetic_oralcare.children.create!([{name:'すべて'},{name:'口臭防止/エチケット用品'},{name:'歯ブラシ'},{name:'その他'}])
cosmetic_relax.children.create!([{name:'すべて'},{name:'エッセンシャルオイル'},{name:'芳香器'},{name:'お香/香炉'},{name:'キャンドル'},{name:'リラクゼーショングッズ'},{name:'その他'}])
cosmetic_diet.children.create!([{name:'すべて'},{name:'ダイエット食品'},{name:'エクササイズ用品'},{name:'体重計'},{name:'体脂肪計'},{name:'その他'}])
cosmetic_others.children.create!([{name:'すべて'},{name:'健康用品'},{name:'看護/介護用品'},{name:'救急/衛生用品'},{name:'その他'}])



electronics_phone = electronics.children.create!(name:'スマートフォン/携帯電話')
electronics_phone_acce = electronics.children.create!(name:'スマホアクセサリー')
electronics_pc = electronics.children.create!(name:'PC/タブレット')
electronics_camera = electronics.children.create!(name:'カメラ')
electronics_tv = electronics.children.create!(name:'テレビ/映像機器')
electronics_audio = electronics.children.create!(name:'オーディオ機器')
electronics_beauty = electronics.children.create!(name:'美容/健康')
electronics_aircon = electronics.children.create!(name:'冷暖房/空調')
electronics_life = electronics.children.create!(name:'生活家電')
electronics_others = electronics.children.create!(name:'その他')

electronics_phone.children.create!([{name:'すべて'},{name:'スマートフォン本体'},{name:'バッテリー/充電器'},{name:'携帯電話本体'},{name:'PHS本体'},{name:'その他'}])
electronics_phone_acce.children.create!([{name:'すべて'},{name:'Android用ケース'},{name:'iPhone用ケース'},{name:'カバー'},{name:'イヤホンジャック'},{name:'ストラップ'},{name:'フィルム'},{name:'自撮り棒'},{name:'その他'}])
electronics_pc.children.create!([{name:'すべて'},{name:'タブレット'},{name:'ノートPC'},{name:'デスクトップ型PC'},{name:'ディスプレイ'},{name:'電子ブックリーダー'},{name:'PC周辺機器'},{name:'PCパーツ'},{name:'その他'}])
electronics_camera.children.create!([{name:'すべて'},{name:'デジタルカメラ'},{name:'ビデオカメラ'},{name:'レンズ(単焦点)', size_tag:9},{name:'レンズ(ズーム)', size_tag:9},{name:'フィルムカメラ'},{name:'防犯カメラ'},{name:'その他'}])
electronics_tv.children.create!([{name:'すべて', size_tag:8},{name:'テレビ', size_tag:8},{name:'プロジェクター', size_tag:8},{name:'ブルーレイレコーダー', size_tag:8},{name:'DVDレコーダー', size_tag:8},{name:'ブルーレイプレーヤー', size_tag:8},{name:'DVDプレーヤー', size_tag:8},{name:'映像用ケーブル', size_tag:8},{name:'その他', size_tag:8}])
electronics_audio.children.create!([{name:'すべて'},{name:'ポータブルプレーヤー'},{name:'イヤフォン'},{name:'ヘッドフォン'},{name:'アンプ'},{name:'スピーカー'},{name:'ケーブル/シールド'},{name:'ラジオ'},{name:'その他'}])
electronics_beauty.children.create!([{name:'すべて'},{name:'ヘアドライヤー'},{name:'ヘアアイロン'},{name:'美容機器'},{name:'電気シェーバー'},{name:'電動歯ブラシ'},{name:'その他'}])
electronics_aircon.children.create!([{name:'すべて'},{name:'エアコン'},{name:'空気清浄器'},{name:'加湿器'},{name:'扇風機'},{name:'除湿機'},{name:'ファンヒーター'},{name:'電気ヒーター'},{name:'オイルヒーター'},{name:'ストーブ'},{name:'ホットカーペット'},{name:'こたつ'},{name:'電気毛布'},{name:'その他'}])
electronics_life.children.create!([{name:'すべて'},{name:'冷蔵庫'},{name:'洗濯機'},{name:'炊飯器'},{name:'電子レンジ/オーブン'},{name:'調理機器'},{name:'アイロン'},{name:'掃除機'},{name:'エスプレッソマシン'},{name:'コーヒーメーカー'},{name:'衣類乾燥機'},{name:'その他'}])
electronics_others.children.create!([{name:'すべて'},{name:'その他'}])


sport_golf = sport.children.create!(name:'ゴルフ')
sport_fishing = sport.children.create!(name:'フィッシング')
sport_bike = sport.children.create!(name:'自転車')
sport_training = sport.children.create!(name:'トレーニング/エクササイズ')
sport_baseball = sport.children.create!(name:'野球')
sport_soccer = sport.children.create!(name:'サッカー/フットサル')
sport_tennis = sport.children.create!(name:'テニス')
sport_board = sport.children.create!(name:'スノーボード')
sport_sky = sport.children.create!(name:'スキー')
sport_various = sport.children.create!(name:'その他スポーツ')
sport_outdoor = sport.children.create!(name:'アウトドア')
sport_others = sport.children.create!(name:'その他')

sport_golf.children.create!([{name:'すべて'},{name:'クラブ'},{name:'ウエア(男性用)'},{name:'ウエア(女性用)'},{name:'バッグ'},{name:'シューズ(男性用)'},{name:'シューズ(女性用)'},{name:'アクセサリー'},{name:'その他'}])
sport_fishing.children.create!([{name:'すべて'},{name:'ロッド'},{name:'リール'},{name:'ルアー用品'},{name:'ウエア'},{name:'釣り糸/ライン'},{name:'その他'}])
sport_bike.children.create!([{name:'すべて'},{name:'自転車本体'},{name:'ウエア'},{name:'パーツ'},{name:'アクセサリー'},{name:'バッグ'},{name:'工具/メンテナンス'},{name:'その他'}])
sport_training.children.create!([{name:'すべて'},{name:'ランニング'},{name:'ウォーキング'},{name:'ヨガ'},{name:'トレーニング用品'},{name:'その他'}])
sport_baseball.children.create!([{name:'すべて'},{name:'ウェア'},{name:'シューズ'},{name:'グローブ'},{name:'バット'},{name:'アクセサリー'},{name:'防具'},{name:'練習機器'},{name:'記念グッズ'},{name:'応援グッズ'},{name:'その他'}])
sport_soccer.children.create!([{name:'すべて'},{name:'ウェア'},{name:'シューズ'},{name:'ボール'},{name:'アクセサリー'},{name:'記念グッズ'},{name:'応援グッズ'},{name:'その他'}])
sport_tennis.children.create!([{name:'すべて'},{name:'ラケット(硬式用)'},{name:'ラケット(軟式用)'},{name:'ウェア'},{name:'シューズ'},{name:'ボール'},{name:'アクセサリー'},{name:'記念グッズ'},{name:'応援グッズ'},{name:'その他'}])
sport_board.children.create!([{name:'すべて'},{name:'ボード', size_tag:14},{name:'バインディング'},{name:'ブーツ(男性用)'},{name:'ブーツ(女性用)'},{name:'ブーツ(子ども用)'},{name:'ウエア/装備(男性用)'},{name:'ウエア/装備(女性用)'},{name:'ウエア/装備(子ども用)'},{name:'アクセサリー'},{name:'バッグ'},{name:'その他'}])
sport_sky.children.create!([{name:'すべて'},{name:'板', size_tag:13},{name:'ブーツ(男性用)'},{name:'ブーツ(女性用)'},{name:'ブーツ(子ども用)'},{name:'ビンディング'},{name:'ウエア(男性用)'},{name:'ウエア(女性用)'},{name:'ウエア(子ども用)'},{name:'ストック'},{name:'その他'}])
sport_various.children.create!([{name:'すべて'},{name:'ダンス/バレエ'},{name:'サーフィン'},{name:'バスケットボール'},{name:'バドミントン'},{name:'バレーボール'},{name:'スケートボード'},{name:'陸上競技'},{name:'ラグビー'},{name:'アメリカンフットボール'},{name:'ボクシング'},{name:'ボウリング'},{name:'その他'}])
sport_others.children.create!([{name:'すべて'},{name:'テント/タープ'},{name:'ライト/ランタン'},{name:'寝袋/寝具'},{name:'テーブル/チェア'},{name:'ストーブ/コンロ'},{name:'調理器具'},{name:'食器'},{name:'登山用品'},{name:'その他'}])




handmade_lady_acce = handmade.children.create!(name:'アクセサリー(女性用)')
handmade_fashion = handmade.children.create!(name:'ファッション/小物')
handmade_acce = handmade.children.create!(name:'アクセサリー/時計')
handmade_item = handmade.children.create!(name:'日用品/インテリア')
handmade_hobby = handmade.children.create!(name:'趣味/おもちゃ')
handmade_kids = handmade.children.create!(name:'キッズ/ベビー')
handmade_material = handmade.children.create!(name:'素材/材料')
handmade_creation = handmade.children.create!(name:'二次創作物')
handmade_others = handmade.children.create!(name:'その他')

handmade_lady_acce.children.create!([{name:'すべて'},{name:'ピアス'},{name:'イヤリング'},{name:'ネックレス'},{name:'ブレスレット'},{name:'リング'},{name:'チャーム'},{name:'ヘアゴム'},{name:'アンクレット'},{name:'その他'}])
handmade_fashion.children.create!([{name:'すべて'},{name:'バッグ(女性用)'},{name:'バッグ(男性用)'},{name:'財布(女性用)'},{name:'財布(男性用)'},{name:'ファッション雑貨'},{name:'その他'}])
handmade_acce.children.create!([{name:'すべて'},{name:'アクセサリー(男性用)'},{name:'時計(女性用)'},{name:'時計(男性用)'},{name:'その他'}])
handmade_item.children.create!([{name:'すべて'},{name:'キッチン用品'},{name:'家具'},{name:'文房具'},{name:'アート/写真'},{name:'アロマ/キャンドル'},{name:'フラワー/ガーデン'},{name:'その他'}])
handmade_hobby.children.create!([{name:'すべて'},{name:'クラフト/布製品'},{name:'おもちゃ/人形'},{name:'その他'}])
handmade_kids.children.create!([{name:'すべて'},{name:'ファッション雑貨'},{name:'スタイ/よだれかけ'},{name:'外出用品'},{name:'ネームタグ'},{name:'その他'}])
handmade_material.children.create!([{name:'すべて'},{name:'各種パーツ'},{name:'生地/糸'},{name:'型紙/パターン'},{name:'その他'}])
handmade_creation.children.create!([{name:'すべて'},{name:'Ingress'},{name:'クリエイターズ宇宙兄弟'},{name:'シンデレラガールズCPグッズ'}])
handmade_others.children.create!([{name:'すべて'}])


ticket_music = ticket.children.create!(name:'音楽')
ticket_sport = ticket.children.create!(name:'スポーツ')
ticket_theater = ticket.children.create!(name:'演劇/芸能')
ticket_event = ticket.children.create!(name:'イベント')
ticket_movie = ticket.children.create!(name:'映画')
ticket_facility = ticket.children.create!(name:'施設利用券')
ticket_coupon = ticket.children.create!(name:'優待券/割引券')
ticket_others = ticket.children.create!(name:'その他')

ticket_music.children.create!([{name:'すべて'},{name:'男性アイドル'},{name:'女性アイドル'},{name:'韓流'},{name:'国内アーティスト'},{name:'海外アーティスト'},{name:'音楽フェス'},{name:'声優/アニメ'},{name:'その他'}])
ticket_sport.children.create!([{name:'すべて'},{name:'サッカー'},{name:'野球'},{name:'テニス'},{name:'格闘技/プロレス'},{name:'相撲/武道'},{name:'ゴルフ'},{name:'バレーボール'},{name:'バスケットボール'},{name:'モータースポーツ'},{name:'ウィンタースポーツ'},{name:'その他'}])
ticket_theater.children.create!([{name:'すべて'},{name:'ミュージカル'},{name:'演劇'},{name:'伝統芸能'},{name:'落語'},{name:'お笑い'},{name:'オペラ'},{name:'サーカス'},{name:'バレエ'},{name:'その他'}])
ticket_event.children.create!([{name:'すべて'},{name:'声優/アニメ'},{name:'キッズ/ファミリー'},{name:'トークショー/講演会'},{name:'その他'}])
ticket_movie.children.create!([{name:'すべて'},{name:'邦画'},{name:'洋画'},{name:'その他'}])
ticket_facility.children.create!([{name:'すべて'},{name:'遊園地/テーマパーク'},{name:'美術館/博物館'},{name:'スキー場'},{name:'ゴルフ場'},{name:'フィットネスクラブ'},{name:'プール'},{name:'ボウリング場'},{name:'水族館'},{name:'動物園'},{name:'その他'}])
ticket_coupon.children.create!([{name:'すべて'},{name:'ショッピング'},{name:'レストラン/食事券'},{name:'フード/ドリンク券'},{name:'宿泊券'},{name:'その他'}])
ticket_others.children.create!([{name:'すべて'}])


mobile_body = mobile.children.create!(name:'自動車本体')
mobile_tire = mobile.children.create!(name:'自動車タイヤ/ホイール')
mobile_part = mobile.children.create!(name:'自動車パーツ')
mobile_acce = mobile.children.create!(name:'自動車アクセサリー')
mobile_bike_body = mobile.children.create!(name:'オートバイ車体')
mobile_bike_part = mobile.children.create!(name:'オートバイパーツ')
mobile_bike_acce = mobile.children.create!(name:'オートバイアクセサリー')

mobile_body.children.create!([{name:'すべて'},{name:'国内自動車本体'},{name:'外国自動車本体'}])
mobile_tire.children.create!([{name:'すべて'},{name:'タイヤ/ホイールセット', size_tag:12},{name:'タイヤ', size_tag:12},{name:'ホイール', size_tag:12},{name:'その他'}])
mobile_part.children.create!([{name:'すべて'},{name:'サスペンション'},{name:'ブレーキ'},{name:'外装、エアロパーツ'},{name:'ライト'},{name:'内装品、シート'},{name:'ステアリング'},{name:'マフラー・排気系'},{name:'エンジン、過給器、冷却装置'},{name:'クラッチ、ミッション、駆動系'},{name:'電装品'},{name:'補強パーツ'},{name:'汎用パーツ'},{name:'外国自動車用パーツ'},{name:'その他'}])
mobile_acce.children.create!([{name:'すべて'},{name:'車内アクセサリー'},{name:'カーナビ'},{name:'カーオーディオ'},{name:'車外アクセサリー'},{name:'メンテナンス用品'},{name:'チャイルドシート'},{name:'ドライブレコーダー'},{name:'レーダー探知機'},{name:'カタログ/マニュアル'},{name:'セキュリティ'},{name:'ETC'},{name:'その他'}])
mobile_bike_body.children.create!([{name:'すべて', size_tag:10}])
mobile_bike_part.children.create!([{name:'すべて'},{name:'タイヤ'},{name:'マフラー'},{name:'エンジン、冷却装置'},{name:'カウル、フェンダー、外装'},{name:'サスペンション'},{name:'ホイール'},{name:'シート'},{name:'ブレーキ'},{name:'タンク'},{name:'ライト、ウィンカー'},{name:'チェーン、スプロケット、駆動系'},{name:'メーター'},{name:'電装系'},{name:'ミラー'},{name:'外国オートバイ用パーツ'},{name:'その他'}])
mobile_bike_acce.children.create!([{name:'すべて'},{name:'ヘルメット/シールド', size_tag:11},{name:'バイクウエア/装備'},{name:'アクセサリー'},{name:'メンテナンス'},{name:'カタログ/マニュアル'},{name:'その他'}])




others_wholesell = others.children.create!(name:'まとめ売り')
others_pet = others.children.create!(name:'ペット用品')
others_drink = others.children.create!(name:'食品')
others_alcohol = others.children.create!(name:'飲料/酒')
others_item = others.children.create!(name:'日用品/生活雑貨/旅行')
others_collection = others.children.create!(name:'アンティーク/コレクション')
others_desk_item = others.children.create!(name:'文房具/事務用品')
others_shop_item = others.children.create!(name:'事務/店舗用品')
others_others = others.children.create!(name:'その他')

others_wholesell.children.create!([{name:'すべて'}])
others_pet.children.create!([{name:'すべて'},{name:'ペットフード'},{name:'犬用品'},{name:'猫用品'},{name:'魚用品/水草'},{name:'小動物用品'},{name:'爬虫類/両生類用品'},{name:'かご/おり'},{name:'鳥用品'},{name:'虫類用品'},{name:'その他'}])
others_drink.children.create!([{name:'すべて'},{name:'菓子'},{name:'米'},{name:'野菜'},{name:'果物'},{name:'調味料'},{name:'魚介類(加工食品)'},{name:'肉類(加工食品)'},{name:'その他加工食品'},{name:'その他'}])
others_alcohol.children.create!([{name:'すべて'},{name:'コーヒー'},{name:'ソフトドリンク'},{name:'ミネラルウォーター'},{name:'茶'},{name:'ウイスキー'},{name:'ワイン'},{name:'ブランデー'},{name:'焼酎'},{name:'日本酒'},{name:'ビール、発泡酒'},{name:'その他'}])
others_item.children.create!([{name:'すべて'},{name:'タオル/バス用品'},{name:'日用品/生活雑貨'},{name:'洗剤/柔軟剤'},{name:'旅行用品'},{name:'防災関連グッズ'},{name:'その他'}])
others_collection.children.create!([{name:'すべて'},{name:'雑貨'},{name:'工芸品'},{name:'家具'},{name:'印刷物'},{name:'その他'}])
others_desk_item.children.create!([{name:'すべて'},{name:'筆記具'},{name:'ノート/メモ帳'},{name:'テープ/マスキングテープ'},{name:'カレンダー/スケジュール'},{name:'アルバム/スクラップ'},{name:'ファイル/バインダー'},{name:'はさみ/カッター'},{name:'カードホルダー/名刺管理'},{name:'のり/ホッチキス'},{name:'その他'}])
others_shop_item.children.create!([{name:'すべて'},{name:'オフィス用品一般'},{name:'オフィス家具'},{name:'店舗用品'},{name:'OA機器'},{name:'ラッピング/包装'},{name:'その他'}])
others_others.children.create!([{name:'すべて'}])